### ISSUE TITLE
any sound is detected as wake word

### ISSUE THREAD

**Issue by hanzala123** [OpenVoiceOS/ovos-ww-plugin-nyumaya#1]
I installed numaya and i was very impressed with that. So I installed this plugin but now the the wake word triggers at any sound. I also tried different sensitivities(even 0.1). This is a consistent problem with mycroft. When i use snowboy independently i get very good results but with mycroft i can't get that to work until i increase the sensitivity at which point very sound triggers the wake word. I couldn't even get my own precise model to be working correctly. That too works only when very close but works flawlessly when used with precise-listen. Other models mike and chistopher suffer from the same problem.
these are my models:

1. snowboy (https://github.com/hanzala123/models)
2. precise (https://github.com/hanzala123/jarvis-model)

Note: my goal is to create a single word wake word like Jarvis or Friday. And secondly make it so that it will only trigger by my voice as if anyone can trigger it then it will be security issue in my use case.

Please help.

**Comment by JarbasAl** [comment]
I'm afraid i can't be of much help, you can change your mycroft.conf to save the wake-words/utterances and inspect the audio for obvious problems

in my experience the mycroft speech listener lowers the volume considerably, using arecord i get regular volume, using the mycroft speech client the volume is really really low. I'm not sure what the cause is, but it's something i'm looking into!

While this issue is not technically about this repo i will leave it open for now, i will post here once i finish my alternate standalone speech client, using the ring buffer and arecord utils in this repo

**Comment by hanzala123** [comment]
@JarbasAl  after some debugging i found out that mycroft switches to pocket sphinx instead of nyumaya because it cannot find libnyumaya.so for arm7l : 

`OSError: /home/pi/mycroft-core/.venv/lib/python3.7/site-packages/jarbas_wake_word_plugin_nyumaya/lib/armv7l/libnyumaya.so: cannot open shared object file: No such file or directory`

also i increased the chunk size on the listener.py by changing line 306 to:

`self.microphone = MutableMicrophone(device_index, rate,
                                            mute=self.mute_calls > 0, chunk_size=2048)`

and disbabled the logging of mic latency  in mic.py(line 111) of the same directory and now i can use your snowboy plugin without any problems.

**Comment by JarbasAl** [comment]
oh, there's a typo in there, thanks for the logs! the actual folder is named `armv7`
